using './main.bicep'

param namePrefix = 'voiceops'
param location = 'eastus2'
param containerImage = 'YOUR_REGISTRY.azurecr.io/voiceops-sentinel:0.1.0'
param azureOpenAiEndpoint = 'https://YOUR_OPENAI_RESOURCE.openai.azure.com'
param azureOpenAiDeployment = 'YOUR_CHAT_DEPLOYMENT'
param azureOpenAiModel = 'YOUR_MODEL_NAME'
param azureOpenAiApiVersion = 'YOUR_API_VERSION'
param communicationEndpoint = 'https://YOUR_ACS_RESOURCE.communication.azure.com'
param communicationCallbackUrl = 'https://YOUR_PUBLIC_HOST/integrations/acs/events'
param mediaWebSocketUrl = 'wss://YOUR_PUBLIC_HOST/media'
param speechEndpoint = 'https://YOUR_SPEECH_RESOURCE.cognitiveservices.azure.com/'
param speechRegion = 'eastus2'
param entraIssuer = 'https://login.microsoftonline.com/YOUR_TENANT_ID/v2.0'
param entraAudience = 'api://YOUR_API_CLIENT_ID'
